version: "3"

services:
  bot:
    build: .
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DEBUG: false

  mongodb:
    image: mongo
    volumes:
      - /var/lib/parrot-bot:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}